/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'fact' : IDL.Text,
  'correct' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Int))],
      [],
    ),
  'getQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getSiteVisits' : IDL.Func([], [IDL.Nat], []),
  'incrementSiteVisits' : IDL.Func([], [IDL.Nat], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'fact' : IDL.Text,
    'correct' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Int))],
        [],
      ),
    'getQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getSiteVisits' : IDL.Func([], [IDL.Nat], []),
    'incrementSiteVisits' : IDL.Func([], [IDL.Nat], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };